---
title: "DS 2020 Final Projects"
author: "Ben Moolan"
output:
  xaringan::moon_reader:
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Final Project Basics

-   team based project (2 - 3 members)

-   maximum of 5 members, larger teams are expected to deliver longer report

-   each individual is expected to ask at least 2 questions based on the data. Thus, each individual is expected to make at least two visuals in the report

-   real-world datasets are highly encouraged

---

## Final Project Evaluation

- Report (22.5% of entire grade)
  - the report evaluation rubric will be posted on Canvas

- Presentation (7.5% of entire grade)

- Extra credit
  - use real-world dataset
  - submit proposal on Canvas
  - submit report draft on Canvas
  - ...

---

## Timeline

-   Early April: Project proposal due

-   Late April: Report draft due

-   May 4 and May 6: In-class presentations

-   May 11: Additional presentation time during the final exam block (if needed)

-   Final report due in May

---

## Project Proposal

-   Research topic (title)

-   Team members

-   Data

-   Questions to be addressed

---

## Final Report

Your final project report is expected to be structured as the following:

-   Introduction / background

-   Data
    -   Could include data processing

-   Methods if applicable

-   Results
    -   Your findings

-   Conclusion

Take a look at [A good example from previous semester](https://github.com/BraedenCollings/Final-Project-DS202)

---

## Final Presentation

-   You will select a time slot for your final presentation on May 4 or May 6 during regular class time, with May 11 available if additional presentation time is needed

-   The length of your presentation time slot depends on the number of students on your team. Each student is expected to have 5 minutes; e.g. a team of 3 students will have 15 minutes for the final presentation

-   You will make slides (PowerPoint/Keynote/Google Slides) for your final presentation covering the intro, data, main results, and conclusion of your project












